/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */

import javax.swing.UIManager;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.OracleConnection;

public class BranchTransactions extends javax.swing.JFrame {

    /**
     * Creates new form BranchTransactions
     */
    static String branchID="b001";
    static String empID="";
    public BranchTransactions(String id) {
        initComponents();
        setTitle("eBanking");
        this.empID=id;
        branchID=getBranchID();
    }
    String getBranchID()
    {
        String ans="";
        String url="jdbc:oracle:thin:@localhost:1521:orcl";
        PreparedStatement pst=null;
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            System.out.println("Driver Loaded !");
            try (Connection con = DriverManager.getConnection(url,"system","pksinha786")) {
                System.out.println("Connection Established ! "+ con);
                try ( //getBranchId(empId in varchar2,bid out varchar2)
                        CallableStatement callstmt = con.prepareCall("{CALL getBranchId(?,?)}")) {
                    System.out.println("Here");
                    callstmt.registerOutParameter(2,Types.VARCHAR);
                    callstmt.setString(1,empID);
                    System.out.println("Here");
                    callstmt.execute();
                    System.out.println("Here");
                    ans=callstmt.getString(2);
                    System.out.println(ans);
                }
                con.close();
            }
        }
        catch(ClassNotFoundException e){
            System.out.println("Driver Not Loaded !");
        }
        catch(SQLException e){
            System.out.println("Connection Not Established ! "+ e);
        }
        return ans;
    }
    
    public class Transaction{
        private String tid;
        private String facc;
        private String tacc;
        private String tbid;
        private String fbid;
        private String Action;
        private String amt;
        Transaction(String tid,String facc,String tacc,String fbid,String tbid,String Action,String amt){
            this.tid = tid;
            this.facc = facc;
            this.tacc = tacc;
            this.fbid = fbid;
            this.tbid  = tbid;
            this.Action = Action;
            this.amt = amt;
        }
        public void addListtoTable(ArrayList<Transaction> list){
            DefaultTableModel model  = (DefaultTableModel) jTable1.getModel();
            
            Object rowData[] = new Object[7];
            for(int i=0;i<list.size();i++){
                rowData[0] = list.get(i).tid;
                rowData[1] = list.get(i).facc;
                rowData[2] = list.get(i).tacc;
                rowData[3] = list.get(i).fbid;
                rowData[4] = list.get(i).tbid;
                rowData[5] = list.get(i).Action;
                rowData[6] = list.get(i).amt;
                model.addRow(rowData);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "T. ID", "From ACC", "To ACC", "From Branch", "To Branchl", "Description", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Branch Transaction");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(197, 197, 197))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        String url = "jdbc:oracle:thin:@localhost:1521:orcl";
       PreparedStatement pst = null;
       //accID="a001";
       ResultSet rs = null;
        try{
          Class.forName("oracle.jdbc.driver.OracleDriver");
          System.out.println("Driver Loaded");
          Connection conn = DriverManager.getConnection(url,"system","pksinha786");
          System.out.println("Connection Established");
          //seeTopTransactionsofBranch(bid in varchar2,result out varchar2 ,flag out number)
           CallableStatement callstmt = conn.prepareCall("{CALL seeTopTransactionsofBranch(?,?,?)}");
		callstmt.registerOutParameter(3,Types.INTEGER);
                callstmt.registerOutParameter(2,Types.LONGVARCHAR);
		callstmt.setString(1,branchID);
                callstmt.execute();
		int flag = callstmt.getInt(3);
                String data = callstmt.getString(2);
                //System.out.println(accID);
                //System.out.println(data);
                String[] rowSplit = data.split(";");
                ArrayList<BranchTransactions.Transaction> trans = new ArrayList<BranchTransactions.Transaction>();
                for(int i=0;i<rowSplit.length;i++){
                    BranchTransactions.Transaction obj=null;
                    String [] valueSplit = rowSplit[i].split(",");
                    for(int j=0;j<valueSplit.length;j++){
                           String tid = valueSplit[0];
                            String facc = valueSplit[1];
                            String tacc = valueSplit[2];
                            String tbid = valueSplit[3];
                            String fbid = valueSplit[4];
                            String Action = valueSplit[5];
                            String amt = valueSplit[6];
                             obj = new BranchTransactions.Transaction(tid,facc,tacc,tbid,fbid,Action,amt);
                            
                                       }
                    trans.add(obj);
                }
                DefaultTableModel model  = (DefaultTableModel) jTable1.getModel();
            
            Object rowData[] = new Object[7];
            for(int i=0;i<trans.size();i++){
                rowData[0] = trans.get(i).tid;
                rowData[1] = trans.get(i).facc;
                rowData[2] = trans.get(i).tacc;
                rowData[3] = trans.get(i).fbid;
                rowData[4] = trans.get(i).tbid;
                rowData[5] = trans.get(i).Action;
                rowData[6] = trans.get(i).amt;
                model.addRow(rowData);
            }    
                if(flag==0){
                     System.out.println("not found");
                     
                }
                else{
                     System.out.println("found");
                      
                }
		
		callstmt.close();  
              conn.close();
                  }
        catch(ClassNotFoundException e){
            System.out.println("Driver Not loaded");
        }
        catch(SQLException e){
            System.out.println("Connection not established "+e);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                /*if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }*/
                UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BranchTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BranchTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BranchTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BranchTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BranchTransactions(empID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
