/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
import javax.swing.UIManager;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.OracleConnection;
public class TopUserTransactions extends javax.swing.JFrame {

    /**
     * Creates new form TopUserTransactions
     */
    //getAccountId(custId in varchar2,accId out varchar2)
    String accID="";
    static String customerId;
    public TopUserTransactions(String custID) {
        initComponents();
        setTitle("eBanking");
        customerId=custID;
        accID=getAccountId();
        System.out.println(customerId);
        System.out.println("--"+accID);
    }
    public class Transaction{
        private String tid;
        private String facc;
        private String tacc;
        private String tbid;
        private String fbid;
        private String Action;
        private String amt;
        Transaction(String tid,String facc,String tacc,String fbid,String tbid,String Action,String amt){
            this.tid = tid;
            this.facc = facc;
            this.tacc = tacc;
            this.fbid = fbid;
            this.tbid  = tbid;
            this.Action = Action;
            this.amt = amt;
        }
        public void addListtoTable(ArrayList<Transaction> list){
            DefaultTableModel model  = (DefaultTableModel) jTable1.getModel();
            
            Object rowData[] = new Object[7];
            for(int i=0;i<list.size();i++){
                rowData[0] = list.get(i).tid;
                rowData[1] = list.get(i).facc;
                rowData[2] = list.get(i).tacc;
                rowData[3] = list.get(i).fbid;
                rowData[4] = list.get(i).tbid;
                rowData[5] = list.get(i).Action;
                rowData[6] = list.get(i).amt;
                model.addRow(rowData);
            }
        }
    }
    
    String getAccountId()
    {
        String acc="";
        String url="jdbc:oracle:thin:@localhost:1521:orcl";
        PreparedStatement pst=null;
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            System.out.println("Driver Loaded !");
            try (Connection con = DriverManager.getConnection(url,"system","pksinha786")) {
                System.out.println("Connection Established ! "+ con);
                try ( //getAccountId(custId in varchar2,accId out varchar2)
                        CallableStatement callstmt = con.prepareCall("{CALL getAccountId(?,?)}")) {
                    System.out.println("Here");
                    callstmt.registerOutParameter(2,Types.VARCHAR);
                    System.out.println(customerId);
                    callstmt.setString(1,customerId);
                    System.out.println("Here");
                    callstmt.execute();
                    System.out.println("Here");
                    acc=callstmt.getString(2);
                    System.out.println(customerId);
                    System.out.println(acc);
                }
                con.close();
            }
        }
        catch(ClassNotFoundException e){
            System.out.println("Driver Not Loaded !");
        }
        catch(SQLException e){
            System.out.println("Connection Not Established ! "+ e);
        }
        return acc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("TRANSACTIONS");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "T. ID", "From Acc.", "To Acc.", "From Branch", "To Branch", "Action", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton1.setText("CLOSE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton2.setText("SHOW ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(163, 163, 163))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //miniStatement(accid in varchar2,result out varchar2 ,flag out number)
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       String url = "jdbc:oracle:thin:@localhost:1521:orcl";
       PreparedStatement pst = null;
       //accID="a001";
       ResultSet rs = null;
        try{
          Class.forName("oracle.jdbc.driver.OracleDriver");
          System.out.println("Driver Loaded");
          Connection conn = DriverManager.getConnection(url,"system","pksinha786");
          System.out.println("Connection Established");
           CallableStatement callstmt = conn.prepareCall("{CALL miniStatement(?,?,?)}");
		callstmt.registerOutParameter(3,Types.INTEGER);
                callstmt.registerOutParameter(2,Types.LONGVARCHAR);
		callstmt.setString(1,accID);
                callstmt.execute();
		int flag = callstmt.getInt(3);
                String data = callstmt.getString(2);
                System.out.println(accID);
                System.out.println(data);
                String[] rowSplit = data.split(";");
                ArrayList<Transaction> trans = new ArrayList<Transaction>();
                for(int i=0;i<rowSplit.length;i++){
                    Transaction obj=null;
                    String [] valueSplit = rowSplit[i].split(",");
                    for(int j=0;j<valueSplit.length;j++){
                           String tid = valueSplit[0];
                            String facc = valueSplit[1];
                            String tacc = valueSplit[2];
                            String tbid = valueSplit[3];
                            String fbid = valueSplit[4];
                            String Action = valueSplit[5];
                            String amt = valueSplit[6];
                             obj = new Transaction(tid,facc,tacc,tbid,fbid,Action,amt);
                            
                                       }
                    trans.add(obj);
                }
                DefaultTableModel model  = (DefaultTableModel) jTable1.getModel();
            
            Object rowData[] = new Object[7];
            for(int i=0;i<trans.size();i++){
                rowData[0] = trans.get(i).tid;
                rowData[1] = trans.get(i).facc;
                rowData[2] = trans.get(i).tacc;
                rowData[3] = trans.get(i).fbid;
                rowData[4] = trans.get(i).tbid;
                rowData[5] = trans.get(i).Action;
                rowData[6] = trans.get(i).amt;
                model.addRow(rowData);
            }    
                if(flag==0){
                     System.out.println("not found");
                     
                }
                else{
                     System.out.println("found");
                      
                }
		
		callstmt.close();  
              conn.close();
                  }
        catch(ClassNotFoundException e){
            System.out.println("Driver Not loaded");
        }
        catch(SQLException e){
            System.out.println("Connection not established "+e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                /*if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }*/
                UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TopUserTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TopUserTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TopUserTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TopUserTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TopUserTransactions(customerId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
